<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('password', 191);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->string('username', 191)->unique();
            $table->boolean('can_delete_banners')->default(true);
            $table->boolean('can_delete_categories')->default(true);
            $table->boolean('can_delete_orders')->default(true);
            $table->boolean('can_delete_products')->default(true);
            $table->boolean('can_delete_promo_codes')->default(true);
            $table->boolean('can_manage_banners')->default(true);
            $table->boolean('can_manage_categories')->default(true);
            $table->boolean('can_manage_orders')->default(true);
            $table->boolean('can_manage_products')->default(true);
            $table->boolean('can_manage_promo_codes')->default(true);
            $table->string('role', 191)->default('ADMIN');
            $table->boolean('can_delete_brands')->default(true);
            $table->boolean('can_manage_brands')->default(true);
            $table->boolean('can_manage_reviews')->default(true);
            $table->dateTime('archived_at')->nullable();
            $table->dateTime('disabled_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('user_permissions', function (Blueprint $table) {
            $table->string('user_id', 191);
            $table->string('permission', 191);
            $table->dateTime('created_at');
            $table->primary(['user_id', 'permission']);
            $table->index('user_id');
            $table->index('created_at');
        });
        Schema::create('admin_audit_logs', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('actor_id', 191)->nullable();
            $table->string('action', 191);
            $table->string('entity_type', 191);
            $table->string('entity_id', 191)->nullable();
            $table->json('metadata')->nullable();
            $table->dateTime('created_at');
            $table->index('actor_id');
            $table->index('entity_id');
            $table->index('created_at');
        });
        Schema::create('admin_login_attempts', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('key_hash', 191);
            $table->string('scope', 191);
            $table->boolean('successful')->default(false);
            $table->dateTime('created_at');
            $table->index('created_at');
        });
        Schema::create('main_categories', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('name', 191)->unique();
            $table->string('slug', 191)->unique();
            $table->text('description')->nullable();
            $table->text('image')->nullable();
            $table->boolean('is_active')->default(true);
            $table->boolean('show_in_nav')->default(true);
            $table->integer('nav_order')->default(0);
            $table->boolean('is_featured')->default(false);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('categories', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('name', 191);
            $table->text('description')->nullable();
            $table->text('image')->nullable();
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->boolean('is_featured')->default(false);
            $table->boolean('is_active')->default(true);
            $table->string('slug', 191)->unique();
            $table->string('brand_id', 191);
            $table->string('main_category_id', 191)->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->unique(['brand_id', 'name']);
            $table->index('created_at');
            $table->index('brand_id');
            $table->index('main_category_id');
            $table->index('archived_at');
        });
        Schema::create('products', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('name', 191);
            $table->string('name_ar', 191)->nullable();
            $table->string('name_en', 191)->nullable();
            $table->string('slug', 191)->unique();
            $table->text('images');
            $table->boolean('is_trending')->default(false);
            $table->text('description')->nullable();
            $table->text('description_ar')->nullable();
            $table->text('description_en')->nullable();
            $table->decimal('price', 10, 2);
            $table->decimal('discount_price', 10, 2)->nullable();
            $table->text('discount_type')->nullable();
            $table->decimal('discount_value', 10, 2)->nullable();
            $table->integer('stock')->default(0);
            $table->text('options')->nullable();
            $table->string('category_id', 191);
            $table->text('packaging')->nullable();
            $table->text('items_per_package')->nullable();
            $table->integer('min_order')->default(1);
            $table->boolean('hide_price')->default(false);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->string('sku', 191)->nullable();
            $table->string('brand_id', 191);
            $table->string('main_category_id', 191)->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->index('category_id');
            $table->index('created_at');
            $table->index('brand_id');
            $table->index('main_category_id');
            $table->index('archived_at');
        });
        Schema::create('brands', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('name', 191)->unique();
            $table->string('name_en', 191)->nullable();
            $table->string('slug', 191)->unique();
            $table->text('description')->nullable();
            $table->text('image')->nullable();
            $table->string('group', 191)->default('DIFFERENT');
            $table->boolean('is_active')->default(true);
            $table->boolean('is_featured')->default(false);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->string('main_category_id', 191)->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('main_category_id');
            $table->index('archived_at');
        });
        Schema::create('orders', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->unsignedBigInteger('order_number')->unique();
            $table->decimal('total_amount', 10, 2);
            $table->string('status', 191)->default('PENDING');
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->text('city');
            $table->text('street_address');
            $table->text('Name');
            $table->string('phone', 191);
            $table->text('shop_name')->nullable();
            $table->text('notes')->nullable();
            $table->text('cancellation_reason')->nullable();
            $table->decimal('discount', 10, 2)->default(0);
            $table->string('promo_code_id', 191)->nullable();
            $table->string('customer_id', 191)->nullable();
            $table->boolean('stock_reserved')->default(true);
            $table->string('idempotency_key', 191)->nullable()->unique();
            $table->string('request_hash', 191)->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('promo_code_id');
            $table->index('customer_id');
            $table->index('archived_at');
        });
        Schema::create('banners', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->text('title')->nullable();
            $table->text('subtitle')->nullable();
            $table->text('title_ar')->nullable();
            $table->text('subtitle_ar')->nullable();
            $table->text('image');
            $table->text('button_text')->nullable();
            $table->text('button_text_ar')->nullable();
            $table->text('link')->nullable();
            $table->text('badge')->nullable();
            $table->text('badge_ar')->nullable();
            $table->boolean('is_active')->default(true);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('promo_codes', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('code', 191)->unique();
            $table->integer('discount_percentage');
            $table->text('delegate_name')->nullable();
            $table->boolean('is_active')->default(true);
            $table->integer('usage_count')->default(0);
            $table->decimal('total_sales', 10, 2)->default(0);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('order_items', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('order_id', 191);
            $table->string('product_id', 191);
            $table->integer('quantity');
            $table->decimal('price', 10, 2);
            $table->text('options')->nullable();
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->index('order_id');
            $table->index('product_id');
            $table->index('created_at');
        });
        Schema::create('inventory_movements', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('order_id', 191)->nullable();
            $table->string('product_id', 191);
            $table->integer('quantity');
            $table->string('type', 191);
            $table->text('reason')->nullable();
            $table->dateTime('created_at');
            $table->string('deduplication_key', 191)->nullable()->unique();
            $table->index('order_id');
            $table->index('product_id');
            $table->index('created_at');
        });
        Schema::create('settings', function (Blueprint $table) {
            $table->string('id', 191)->default('site-settings')->primary();
            $table->json('shipping_policy_content')->nullable();
            $table->json('contact_page_content')->nullable();
            $table->json('privacy_policy_content')->nullable();
            $table->text('categories_cta_title')->nullable();
            $table->text('categories_cta_desc')->nullable();
            $table->text('categories_cta_title_ar')->nullable();
            $table->text('categories_cta_desc_ar')->nullable();
            $table->dateTime('updated_at');
            $table->text('categories_cta_image')->nullable();
            $table->text('express_shipping_time')->nullable();
            $table->text('final_sale_desc')->nullable();
            $table->text('final_sale_desc_ar')->nullable();
            $table->text('final_sale_title')->nullable();
            $table->text('final_sale_title_ar')->nullable();
            $table->text('returns_desc')->nullable();
            $table->text('returns_desc_ar')->nullable();
            $table->text('returns_title')->nullable();
            $table->text('returns_title_ar')->nullable();
            $table->text('shipping_desc')->nullable();
            $table->text('shipping_desc_ar')->nullable();
            $table->text('shipping_title')->nullable();
            $table->text('shipping_title_ar')->nullable();
            $table->text('standard_shipping_time')->nullable();
            $table->text('verification_desc')->nullable();
            $table->text('verification_desc_ar')->nullable();
            $table->text('verification_title')->nullable();
            $table->text('verification_title_ar')->nullable();
            $table->text('hygiene_desc')->nullable();
            $table->text('hygiene_desc_ar')->nullable();
            $table->text('hygiene_title')->nullable();
            $table->text('hygiene_title_ar')->nullable();
            $table->text('shipping_returns_image')->nullable();
            $table->text('about_hero_image')->nullable();
            $table->text('about_hero_subtitle')->nullable();
            $table->text('about_hero_subtitle_ar')->nullable();
            $table->text('about_hero_title')->nullable();
            $table->text('about_hero_title_ar')->nullable();
            $table->text('about_narrative_desc1')->nullable();
            $table->text('about_narrative_desc1_ar')->nullable();
            $table->text('about_narrative_desc2')->nullable();
            $table->text('about_narrative_desc2_ar')->nullable();
            $table->text('about_narrative_image')->nullable();
            $table->text('about_narrative_quote')->nullable();
            $table->text('about_narrative_quote_ar')->nullable();
            $table->text('about_narrative_title')->nullable();
            $table->text('about_narrative_title_ar')->nullable();
            $table->text('about_value1_desc')->nullable();
            $table->text('about_value1_desc_ar')->nullable();
            $table->text('about_value1_title')->nullable();
            $table->text('about_value1_title_ar')->nullable();
            $table->text('about_value2_desc')->nullable();
            $table->text('about_value2_desc_ar')->nullable();
            $table->text('about_value2_title')->nullable();
            $table->text('about_value2_title_ar')->nullable();
            $table->text('about_value3_desc')->nullable();
            $table->text('about_value3_desc_ar')->nullable();
            $table->text('about_value3_title')->nullable();
            $table->text('about_value3_title_ar')->nullable();
            $table->text('about_values_desc')->nullable();
            $table->text('about_values_desc_ar')->nullable();
            $table->text('about_values_title')->nullable();
            $table->text('about_values_title_ar')->nullable();
            $table->text('about_narrative_founded')->nullable();
            $table->text('about_narrative_founded_ar')->nullable();
            $table->text('footer_brand_title')->nullable();
            $table->text('footer_brand_title_ar')->nullable();
            $table->text('footer_brand_tagline')->nullable();
            $table->text('footer_brand_tagline_ar')->nullable();
            $table->text('footer_brand_description')->nullable();
            $table->text('footer_brand_description_ar')->nullable();
            $table->text('footer_copyright')->nullable();
            $table->text('footer_copyright_ar')->nullable();
            $table->text('footer_contact_title')->nullable();
            $table->text('footer_contact_title_ar')->nullable();
            $table->text('footer_address')->nullable();
            $table->text('footer_address_ar')->nullable();
            $table->text('footer_phone')->nullable();
            $table->text('footer_email')->nullable();
            $table->text('footer_instagram_url')->nullable();
            $table->text('footer_facebook_url')->nullable();
            $table->text('footer_whatsapp_url')->nullable();
            $table->text('footer_linkedin_url')->nullable();
            $table->text('whatsapp_number')->nullable();
            $table->text('footer_shop_title')->nullable();
            $table->text('footer_shop_title_ar')->nullable();
            $table->text('footer_support_title')->nullable();
            $table->text('footer_support_title_ar')->nullable();
            $table->text('footer_company_title')->nullable();
            $table->text('footer_company_title_ar')->nullable();
            $table->text('footer_newsletter_title')->nullable();
            $table->text('footer_newsletter_title_ar')->nullable();
            $table->text('footer_newsletter_desc')->nullable();
            $table->text('footer_newsletter_desc_ar')->nullable();
            $table->text('footer_jurisdiction')->nullable();
            $table->text('footer_jurisdiction_ar')->nullable();
            $table->text('footer_terms_url')->nullable();
            $table->text('footer_privacy_url')->nullable();
            $table->text('footer_support_link1_label')->nullable();
            $table->text('footer_support_link1_label_ar')->nullable();
            $table->text('footer_support_link1_url')->nullable();
            $table->text('footer_support_link2_label')->nullable();
            $table->text('footer_support_link2_label_ar')->nullable();
            $table->text('footer_support_link2_url')->nullable();
            $table->text('footer_support_link3_label')->nullable();
            $table->text('footer_support_link3_label_ar')->nullable();
            $table->text('footer_support_link3_url')->nullable();
            $table->text('footer_support_link4_label')->nullable();
            $table->text('footer_support_link4_label_ar')->nullable();
            $table->text('footer_support_link4_url')->nullable();
            $table->text('footer_company_link1_label')->nullable();
            $table->text('footer_company_link1_label_ar')->nullable();
            $table->text('footer_company_link1_url')->nullable();
            $table->text('footer_company_link2_label')->nullable();
            $table->text('footer_company_link2_label_ar')->nullable();
            $table->text('footer_company_link2_url')->nullable();
            $table->text('footer_company_link3_label')->nullable();
            $table->text('footer_company_link3_label_ar')->nullable();
            $table->text('footer_company_link3_url')->nullable();
            $table->text('footer_company_link4_label')->nullable();
            $table->text('footer_company_link4_label_ar')->nullable();
            $table->text('footer_company_link4_url')->nullable();
            $table->string('footer_category1_id', 191)->nullable();
            $table->string('footer_category2_id', 191)->nullable();
            $table->string('footer_category3_id', 191)->nullable();
            $table->string('footer_category4_id', 191)->nullable();
            $table->decimal('exchange_rate', 10, 2)->default(135);
            $table->text('middle_banner1_image')->nullable();
            $table->text('middle_banner1_link')->nullable();
            $table->text('middle_banner2_button_text')->nullable();
            $table->text('middle_banner2_button_text_ar')->nullable();
            $table->text('middle_banner2_image')->nullable();
            $table->text('middle_banner2_link')->nullable();
            $table->text('middle_banner2_subtitle')->nullable();
            $table->text('middle_banner2_subtitle_ar')->nullable();
            $table->text('middle_banner2_title')->nullable();
            $table->text('middle_banner2_title_ar')->nullable();
            $table->text('stat_deliveries')->nullable();
            $table->text('stat_brands')->nullable();
            $table->text('stat_products')->nullable();
            $table->text('stat_clients')->nullable();
            $table->text('home_categories_badge')->nullable();
            $table->text('home_categories_badge_ar')->nullable();
            $table->text('home_categories_title')->nullable();
            $table->text('home_categories_title_ar')->nullable();
            $table->text('home_categories_desc')->nullable();
            $table->text('home_categories_desc_ar')->nullable();
            $table->text('home_categories_stats')->nullable();
            $table->text('home_categories_ids')->nullable();
            $table->text('home_featured_badge')->nullable();
            $table->text('home_featured_badge_ar')->nullable();
            $table->text('home_featured_title')->nullable();
            $table->text('home_featured_title_ar')->nullable();
            $table->text('home_featured_desc')->nullable();
            $table->text('home_featured_desc_ar')->nullable();
            $table->text('home_featured_best_seller_ids')->nullable();
            $table->text('home_featured_new_arrival_ids')->nullable();
            $table->boolean('home_services_enabled')->nullable()->default(true);
            $table->text('home_services_title')->nullable();
            $table->text('home_services_title_ar')->nullable();
            $table->text('home_services_desc')->nullable();
            $table->text('home_services_desc_ar')->nullable();
            $table->text('home_services_items')->nullable();
            $table->boolean('home_trending_weekly_enabled')->nullable()->default(true);
            $table->text('home_trending_weekly_badge')->nullable();
            $table->text('home_trending_weekly_badge_ar')->nullable();
            $table->text('home_trending_weekly_title')->nullable();
            $table->text('home_trending_weekly_title_ar')->nullable();
            $table->text('home_trending_weekly_desc')->nullable();
            $table->text('home_trending_weekly_desc_ar')->nullable();
            $table->text('home_trending_weekly_product_ids')->nullable();
            $table->boolean('home_testimonials_enabled')->nullable()->default(true);
            $table->text('home_testimonials_badge')->nullable();
            $table->text('home_testimonials_badge_ar')->nullable();
            $table->text('home_testimonials_title')->nullable();
            $table->text('home_testimonials_title_ar')->nullable();
            $table->text('home_testimonials_desc')->nullable();
            $table->text('home_testimonials_desc_ar')->nullable();
            $table->text('home_testimonials_items')->nullable();
            $table->index('footer_category1_id');
            $table->index('footer_category2_id');
            $table->index('footer_category3_id');
            $table->index('footer_category4_id');
        });
        Schema::create('reviews', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('product_id', 191);
            $table->integer('rating');
            $table->text('feedback')->nullable();
            $table->text('image')->nullable();
            $table->string('name', 191);
            $table->text('email')->nullable();
            $table->boolean('is_approved')->default(false);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('product_id');
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('customers', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->text('shop_name');
            $table->text('owner_name');
            $table->string('phone', 191)->unique();
            $table->text('city');
            $table->text('address');
            $table->string('password', 191);
            $table->text('notes')->nullable();
            $table->boolean('is_active')->default(false);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('wishlist_items', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('customer_id', 191);
            $table->string('product_id', 191);
            $table->dateTime('created_at');
            $table->unique(['customer_id', 'product_id']);
            $table->index('customer_id');
            $table->index('product_id');
            $table->index('created_at');
        });
        Schema::create('posts', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->text('title');
            $table->text('title_ar')->nullable();
            $table->string('slug', 191)->unique();
            $table->text('excerpt')->nullable();
            $table->text('excerpt_ar')->nullable();
            $table->text('content');
            $table->text('content_ar')->nullable();
            $table->text('image')->nullable();
            $table->text('category');
            $table->text('category_ar')->nullable();
            $table->boolean('is_published')->default(true);
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::create('contact_messages', function (Blueprint $table) {
            $table->string('id', 191)->primary();
            $table->string('name', 191);
            $table->string('phone', 191);
            $table->text('shop_name')->nullable();
            $table->text('city')->nullable();
            $table->text('message');
            $table->boolean('is_read')->default(false);
            $table->text('notes')->nullable();
            $table->text('ip_address')->nullable();
            $table->text('user_agent')->nullable();
            $table->dateTime('created_at');
            $table->dateTime('updated_at');
            $table->dateTime('archived_at')->nullable();
            $table->index('created_at');
            $table->index('archived_at');
        });
        Schema::table('users', function (Blueprint $table) {
            $table->string('remember_token', 100)->nullable();
        });
        Schema::table('user_permissions', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::table('admin_audit_logs', function (Blueprint $table) {
            $table->foreign('actor_id')->references('id')->on('users')->onDelete('set null');
        });
        Schema::table('categories', function (Blueprint $table) {
            $table->foreign('brand_id')->references('id')->on('brands')->onDelete('restrict');
        });
        Schema::table('categories', function (Blueprint $table) {
            $table->foreign('main_category_id')->references('id')->on('main_categories')->onDelete('restrict');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->foreign('brand_id')->references('id')->on('brands')->onDelete('restrict');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->foreign('category_id')->references('id')->on('categories')->onDelete('restrict');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->foreign('main_category_id')->references('id')->on('main_categories')->onDelete('restrict');
        });
        Schema::table('brands', function (Blueprint $table) {
            $table->foreign('main_category_id')->references('id')->on('main_categories')->onDelete('restrict');
        });
        Schema::table('orders', function (Blueprint $table) {
            $table->foreign('promo_code_id')->references('id')->on('promo_codes')->onDelete('restrict');
        });
        Schema::table('orders', function (Blueprint $table) {
            $table->foreign('customer_id')->references('id')->on('customers')->onDelete('restrict');
        });
        Schema::table('order_items', function (Blueprint $table) {
            $table->foreign('order_id')->references('id')->on('orders')->onDelete('cascade');
        });
        Schema::table('order_items', function (Blueprint $table) {
            $table->foreign('product_id')->references('id')->on('products')->onDelete('restrict');
        });
        Schema::table('reviews', function (Blueprint $table) {
            $table->foreign('product_id')->references('id')->on('products')->onDelete('cascade');
        });
        Schema::table('wishlist_items', function (Blueprint $table) {
            $table->foreign('customer_id')->references('id')->on('customers')->onDelete('cascade');
        });
        Schema::table('wishlist_items', function (Blueprint $table) {
            $table->foreign('product_id')->references('id')->on('products')->onDelete('cascade');
        });
        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->string('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
        Schema::create('sequences', function (Blueprint $table) {
            $table->string('name')->primary();
            $table->unsignedBigInteger('value')->default(0);
        });
    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('sequences');
        Schema::dropIfExists('sessions');
        Schema::dropIfExists('contact_messages');
        Schema::dropIfExists('posts');
        Schema::dropIfExists('wishlist_items');
        Schema::dropIfExists('customers');
        Schema::dropIfExists('reviews');
        Schema::dropIfExists('settings');
        Schema::dropIfExists('inventory_movements');
        Schema::dropIfExists('order_items');
        Schema::dropIfExists('promo_codes');
        Schema::dropIfExists('banners');
        Schema::dropIfExists('orders');
        Schema::dropIfExists('brands');
        Schema::dropIfExists('products');
        Schema::dropIfExists('categories');
        Schema::dropIfExists('main_categories');
        Schema::dropIfExists('admin_login_attempts');
        Schema::dropIfExists('admin_audit_logs');
        Schema::dropIfExists('user_permissions');
        Schema::dropIfExists('users');
        Schema::enableForeignKeyConstraints();
    }
};
