-- Create Settings Baseline Table
CREATE TABLE IF NOT EXISTS "Settings" (
    "id" TEXT NOT NULL DEFAULT 'site-settings',
    "categoriesCtaTitle" TEXT DEFAULT 'Looking for specific wholesale brands?',
    "categoriesCtaDesc" TEXT DEFAULT 'Our wholesale team is ready to provide custom pricing and scheduled deliveries for your business.',
    "categoriesCtaTitleAr" TEXT DEFAULT 'تبحث عن شركات أو منتجات محددة؟',
    "categoriesCtaDescAr" TEXT DEFAULT 'فريق المبيعات لدينا جاهز لتزويدكم بأفضل أسعار الجملة وجداول التوزيع المنتظمة.',
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "categoriesCtaImage" TEXT DEFAULT 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-S_GMsoebb73JIEWcxtvH2G-vVgkfypE8ysWpGMNiiiwyTno8rIbMCpHR-fsa76ZQL49aYswb7bGZh-kgwc6z9lv0VwUSUrStxNWz2qU3RuIb75ShOMAKZMRyrOXZHZjEBgtxfW7r97FEEshOkEd2MqgE6FpGYrmKa8msLtMOQxXBsmhr3ZGGEtL7jpzgMYbgrAXhiHcMfCspdvD5FRNuSbgFY9_xGqcJM9KbgG0MoC4Ie4WkkmCR4FsuavfglcnY13G2ADZxlK8F',
    "expressShippingTime" TEXT DEFAULT '24 Hours',
    "finalSaleDesc" TEXT DEFAULT 'All goods are shipped in factory-sealed cases conforming to international standards.',
    "finalSaleDescAr" TEXT DEFAULT 'يتم تسليم البضائع في كراتين المصنع الأصلية والمطابقة للمواصفات القياسية.',
    "finalSaleTitle" TEXT DEFAULT 'Wholesale Delivery Terms',
    "finalSaleTitleAr" TEXT DEFAULT 'شروط تسليم الجملة',
    "returnsDesc" TEXT DEFAULT 'We are committed to full satisfaction and verified shipment handling.',
    "returnsDescAr" TEXT DEFAULT 'نحن ملتزمون بالجودة والمطابقة التامة للشحنات.',
    "returnsTitle" TEXT DEFAULT 'Wholesale Support',
    "returnsTitleAr" TEXT DEFAULT 'دعم الجملة',
    "shippingDesc" TEXT DEFAULT 'We ensure wholesale goods reach your business in perfect condition.',
    "shippingDescAr" TEXT DEFAULT 'نحن نضمن وصول بضائع الجملة إلى نشاطكم التجاري في أفضل حالة.',
    "shippingTitle" TEXT DEFAULT 'Fast & Reliable Distribution',
    "shippingTitleAr" TEXT DEFAULT 'توزيع سريع وموثوق',
    "standardShippingTime" TEXT DEFAULT '1-3 Business Days',
    "verificationDesc" TEXT DEFAULT 'Orders are verified and scheduled immediately with our logistics fleet.',
    "verificationDescAr" TEXT DEFAULT 'يتم التحقق من الطلبات وجدولتها فوراً للتوصيل المباشر لباب المحل.',
    "verificationTitle" TEXT DEFAULT 'Verification Process',
    "verificationTitleAr" TEXT DEFAULT 'عملية التحقق',
    "hygieneDesc" TEXT DEFAULT 'Our temperature-controlled warehouses ensure optimal quality preservation.',
    "hygieneDescAr" TEXT DEFAULT 'تضمن مستودعاتنا وشاحناتنا درجات حرارة وبيئة تخزين مثالية حتى نقطة التسليم.',
    "hygieneTitle" TEXT DEFAULT 'Safety & Temperature Storage',
    "hygieneTitleAr" TEXT DEFAULT 'بروتوكولات السلامة والتخزين',
    "shippingReturnsImage" TEXT DEFAULT '/images/hawa_hero.jpg',
    "aboutHeroImage" TEXT DEFAULT '/images/hawa_wholesale_hub.jpg',
    "aboutHeroSubtitle" TEXT DEFAULT 'Your trusted partner for distributing top quality wholesale FMCG and food products.',
    "aboutHeroSubtitleAr" TEXT DEFAULT 'شريككم الموثوق لتوزيع البضائع والمواد الغذائية من أفضل الشركات والمصانع.',
    "aboutHeroTitle" TEXT DEFAULT 'Our Story in Wholesale Distribution',
    "aboutHeroTitleAr" TEXT DEFAULT 'قصتنا في ريادة وتوزيع الجملة',
    "aboutNarrativeDesc1" TEXT DEFAULT 'At Hawa Distribution, we operate as the vital supply line for grocery retailers, supermarkets, and wholesalers. We partner directly with leading domestic and international food manufacturers to supply authentic, factory-sealed consumer goods at official wholesale rates.',
    "aboutNarrativeDesc1Ar" TEXT DEFAULT 'في شركة حوا للتوزيع والتجارة، نعمل كشريان إمداد رئيسي لأصحاب السوبرماركت والبقالات وتجار الجملة. نربط كبرى المصانع والشركات المنتجة للسلع الغذائية بنقاط البيع مباشرة.',
    "aboutNarrativeDesc2" TEXT DEFAULT 'With temperature-controlled central warehouses and a dedicated logistics fleet covering all Syrian governorates, we guarantee punctual deliveries, verified shelf-life, and transparent purchase invoicing.',
    "aboutNarrativeDesc2Ar" TEXT DEFAULT 'بفضل مستودعاتنا المركزية المجهزة وشبكة التوزيع المنظمة التي تغطي كافة المحافظات السورية، نضمن مواعيد تسليم دقيقة لباب المحل، مع مطابقة تامة للمواصفات وفواتير موثقة.',
    "aboutNarrativeImage" TEXT DEFAULT '/images/hawa_hero.jpg',
    "aboutNarrativeQuote" TEXT DEFAULT 'Connecting you with the world''s finest brands.',
    "aboutNarrativeQuoteAr" TEXT DEFAULT 'جودة مضمونة وخدمة توزيع موثوقة.',
    "aboutNarrativeTitle" TEXT DEFAULT 'Our Mission for Quality Distribution',
    "aboutNarrativeTitleAr" TEXT DEFAULT 'مهمتنا في التوزيع الموثوق',
    "aboutValue1Desc" TEXT DEFAULT 'All products are certified authentic from original manufacturers.',
    "aboutValue1DescAr" TEXT DEFAULT 'جميع المنتجات أصلية 100% ومطابقة لأعلى معايير الجودة والمواصفات.',
    "aboutValue1Title" TEXT DEFAULT 'Certified Quality',
    "aboutValue1TitleAr" TEXT DEFAULT 'جودة ومواصفات قياسية',
    "aboutValue2Desc" TEXT DEFAULT 'Direct distribution partnerships with leading global brands.',
    "aboutValue2DescAr" TEXT DEFAULT 'شراكات توزيع مباشرة مع كبرى العلامات التجارية العالمية.',
    "aboutValue2Title" TEXT DEFAULT '100% Authentic',
    "aboutValue2TitleAr" TEXT DEFAULT 'أصلي 100٪',
    "aboutValue3Desc" TEXT DEFAULT 'Temperature-controlled logistics fleet covering all distribution channels.',
    "aboutValue3DescAr" TEXT DEFAULT 'سيارات وشاحنات مجهزة لنقل وتوزيع البضائع بدقة وكفاءة لباب المحل.',
    "aboutValue3Title" TEXT DEFAULT 'Reliable Fleet',
    "aboutValue3TitleAr" TEXT DEFAULT 'شبكة توزيع مجهزة',
    "aboutValuesDesc" TEXT DEFAULT 'We are committed to transparency, reliability, and excellence in food distribution.',
    "aboutValuesDescAr" TEXT DEFAULT 'نحن ملتزمون بالشفافية والموثوقية والتميز في توزيع البضائع والمواد الغذائية.',
    "aboutValuesTitle" TEXT DEFAULT 'Our Core Values',
    "aboutValuesTitleAr" TEXT DEFAULT 'قيمنا الجوهرية',
    "aboutNarrativeFounded" TEXT DEFAULT 'Founded with Trust',
    "aboutNarrativeFoundedAr" TEXT DEFAULT 'تأسست على الثقة',
    "whatsappNumber" TEXT DEFAULT '+963900000000',
    "exchangeRate" DECIMAL(10,2) NOT NULL DEFAULT 135,
    "middleBanner1Image" TEXT DEFAULT 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1200',
    "middleBanner1Link" TEXT DEFAULT '/products',
    "middleBanner2ButtonText" TEXT DEFAULT 'Explore Catalog',
    "middleBanner2ButtonTextAr" TEXT DEFAULT 'تصفح الكتالوج',
    "middleBanner2Image" TEXT DEFAULT 'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=1200',
    "middleBanner2Link" TEXT DEFAULT '/products',
    "middleBanner2Subtitle" TEXT DEFAULT 'Discover the best products from around the world.',
    "middleBanner2SubtitleAr" TEXT DEFAULT 'اكتشف أفضل المنتجات من كبرى الشركات العالمية.',
    "middleBanner2Title" TEXT DEFAULT 'Global Brands',
    "middleBanner2TitleAr" TEXT DEFAULT 'شركات عالمية',
    "statDeliveries" TEXT DEFAULT '+9000',
    "statBrands" TEXT DEFAULT '+100',
    "statProducts" TEXT DEFAULT '+500',
    "statClients" TEXT DEFAULT '+300',
    CONSTRAINT "Settings_pkey" PRIMARY KEY ("id")
);
